import Head from "next/head";
import { Inter } from "next/font/google";
import Layout from "@/components/Layout";

const inter = Inter({ subsets: ["latin"] });

/* 
  PAGES
    - Home/Landing
    - Login/Registro
    * - Crear nuevo reciclcado
    ? - Buscar productos/usuarios 
    - Perfil/modificar datos / Historial - lista de reciclados
    - FAQ
*/

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1>Bienvenido a Greencycle</h1>
      </Layout>
    </>
  );
}
