import Head from "next/head";
import { Inter } from "next/font/google";
import Layout from "@/components/Layout/Index";
import RegisterForm from "@/components/RegisterForm";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Greencycle - Completá tus datos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1>Completá tus datos</h1>
        <RegisterForm />
      </Layout>
    </>
  );
}
