import Head from "next/head";
import { Inter } from "next/font/google";
import Layout from "@/components/Layout";
import RegisterForm from "@/components/RegisterForm";

const inter = Inter({ subsets: ["latin"] });

export default function Register() {
  return (
    <>
      <Head>
        <title>Greencycle - Registrate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout bg="primary">
        <h1>Registrate</h1>
        <RegisterForm register />
      </Layout>
    </>
  );
}
