import Head from "next/head";
import Layout from "@/components/Layout/Index";
import PedidoDetail from "@/components/PedidoDetail/Index";
import { useRouter } from "next/router";
import { data } from "@/data/data";
import { useState, useEffect } from "react";

export default function Detalles() {
  const [detalle, setDetalle] = useState();
  const router = useRouter();
  const id = router.query;
  const orders = data.orders;

  useEffect(() => {
    const result = orders.find((o) => o.id == id.id);
    setDetalle(result);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {detalle === undefined ? (
          <div>
            <h1>Cargando</h1>
          </div>
        ) : (
          <PedidoDetail prop={detalle} />
        )}
      </Layout>
    </>
  );
}
